- name: restart newrelic
  service:
    name: newrelic-daemon
    state: restarted
    enabled: yes

- name: restart newrelic-sysmond
  service:
    name: newrelic-sysmond
    state: restarted
    enabled: yes

